// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Saladbowl Creative")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2015 Saladbowl Creative")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
