// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Akka.Interfaced CodeGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;
using Akka.Interfaced;

#region SlimHttp.Interface.ICalculator

namespace SlimHttp.Interface
{
    public class ICalculator__Concat__Invoke : IInterfacedMessage
    {
        public System.String a;
        public System.String b;

        public Type GetInterfaceType() { return typeof(ICalculator); }
    }

    public class ICalculator__Concat__Return : IInterfacedMessage, IValueGetable
    {
        public System.String v;

        public Type GetInterfaceType() { return typeof(ICalculator); }

        public object Value { get { return v; } }
    }

    public class ICalculator__Sum__Invoke : IInterfacedMessage
    {
        public System.Int32 a;
        public System.Int32 b;

        public Type GetInterfaceType() { return typeof(ICalculator); }
    }

    public class ICalculator__Sum__Return : IInterfacedMessage, IValueGetable
    {
        public System.Int32 v;

        public Type GetInterfaceType() { return typeof(ICalculator); }

        public object Value { get { return v; } }
    }

    public interface ICalculator_NoReply
    {
        void Concat(System.String a, System.String b);
        void Sum(System.Int32 a, System.Int32 b);
    }

    public class CalculatorRef : InterfacedSlimActorRef, ICalculator_NoReply
    {
        public CalculatorRef(ISlimActorRef actor, ISlimRequestWaiter requestWaiter, TimeSpan? timeout)
            : base(actor, requestWaiter, timeout)
        {
        }

        public ICalculator_NoReply WithNoReply()
        {
            return this;
        }

        public CalculatorRef WithRequestWaiter(ISlimRequestWaiter requestWaiter)
        {
            return new CalculatorRef(Actor, requestWaiter, Timeout);
        }

        public CalculatorRef WithTimeout(TimeSpan? timeout)
        {
            return new CalculatorRef(Actor, RequestWaiter, timeout);
        }

        public Task<System.String> Concat(System.String a, System.String b)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new ICalculator__Concat__Invoke { a = a, b = b }
            };
            return SendRequestAndReceive<System.String>(requestMessage);
        }

        public Task<System.Int32> Sum(System.Int32 a, System.Int32 b)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new ICalculator__Sum__Invoke { a = a, b = b }
            };
            return SendRequestAndReceive<System.Int32>(requestMessage);
        }

        void ICalculator_NoReply.Concat(System.String a, System.String b)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new ICalculator__Concat__Invoke { a = a, b = b }
            };
            SendRequest(requestMessage);
        }

        void ICalculator_NoReply.Sum(System.Int32 a, System.Int32 b)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new ICalculator__Sum__Invoke { a = a, b = b }
            };
            SendRequest(requestMessage);
        }
    }
}

#endregion

#region SlimHttp.Interface.ICounter

namespace SlimHttp.Interface
{
    public class ICounter__IncCounter__Invoke : IInterfacedMessage
    {
        public System.Int32 delta;

        public Type GetInterfaceType() { return typeof(ICounter); }
    }

    public class ICounter__GetCounter__Invoke : IInterfacedMessage
    {
        public Type GetInterfaceType() { return typeof(ICounter); }
    }

    public class ICounter__GetCounter__Return : IInterfacedMessage, IValueGetable
    {
        public System.Int32 v;

        public Type GetInterfaceType() { return typeof(ICounter); }

        public object Value { get { return v; } }
    }

    public interface ICounter_NoReply
    {
        void IncCounter(System.Int32 delta);
        void GetCounter();
    }

    public class CounterRef : InterfacedSlimActorRef, ICounter_NoReply
    {
        public CounterRef(ISlimActorRef actor, ISlimRequestWaiter requestWaiter, TimeSpan? timeout)
            : base(actor, requestWaiter, timeout)
        {
        }

        public ICounter_NoReply WithNoReply()
        {
            return this;
        }

        public CounterRef WithRequestWaiter(ISlimRequestWaiter requestWaiter)
        {
            return new CounterRef(Actor, requestWaiter, Timeout);
        }

        public CounterRef WithTimeout(TimeSpan? timeout)
        {
            return new CounterRef(Actor, RequestWaiter, timeout);
        }

        public Task IncCounter(System.Int32 delta)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new ICounter__IncCounter__Invoke { delta = delta }
            };
            return SendRequestAndWait(requestMessage);
        }

        public Task<System.Int32> GetCounter()
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new ICounter__GetCounter__Invoke {  }
            };
            return SendRequestAndReceive<System.Int32>(requestMessage);
        }

        void ICounter_NoReply.IncCounter(System.Int32 delta)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new ICounter__IncCounter__Invoke { delta = delta }
            };
            SendRequest(requestMessage);
        }

        void ICounter_NoReply.GetCounter()
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new ICounter__GetCounter__Invoke {  }
            };
            SendRequest(requestMessage);
        }
    }
}

#endregion

#region SlimHttp.Interface.IPedantic

namespace SlimHttp.Interface
{
    public class IPedantic__TestCall__Invoke : IInterfacedMessage
    {
        public Type GetInterfaceType() { return typeof(IPedantic); }
    }

    public class IPedantic__TestOptional__Invoke : IInterfacedMessage
    {
        public System.Nullable<System.Int32> value;

        public Type GetInterfaceType() { return typeof(IPedantic); }
    }

    public class IPedantic__TestOptional__Return : IInterfacedMessage, IValueGetable
    {
        public System.Nullable<System.Int32> v;

        public Type GetInterfaceType() { return typeof(IPedantic); }

        public object Value { get { return v; } }
    }

    public class IPedantic__TestTuple__Invoke : IInterfacedMessage
    {
        public System.Tuple<System.Int32, System.String> value;

        public Type GetInterfaceType() { return typeof(IPedantic); }
    }

    public class IPedantic__TestTuple__Return : IInterfacedMessage, IValueGetable
    {
        public System.Tuple<System.Int32, System.String> v;

        public Type GetInterfaceType() { return typeof(IPedantic); }

        public object Value { get { return v; } }
    }

    public class IPedantic__TestParams__Invoke : IInterfacedMessage
    {
        public System.Int32[] values;

        public Type GetInterfaceType() { return typeof(IPedantic); }
    }

    public class IPedantic__TestParams__Return : IInterfacedMessage, IValueGetable
    {
        public System.Int32[] v;

        public Type GetInterfaceType() { return typeof(IPedantic); }

        public object Value { get { return v; } }
    }

    public class IPedantic__TestPassClass__Invoke : IInterfacedMessage
    {
        public SlimHttp.Interface.TestParam param;

        public Type GetInterfaceType() { return typeof(IPedantic); }
    }

    public class IPedantic__TestPassClass__Return : IInterfacedMessage, IValueGetable
    {
        public System.String v;

        public Type GetInterfaceType() { return typeof(IPedantic); }

        public object Value { get { return v; } }
    }

    public class IPedantic__TestReturnClass__Invoke : IInterfacedMessage
    {
        public System.Int32 value;
        public System.Int32 offset;

        public Type GetInterfaceType() { return typeof(IPedantic); }
    }

    public class IPedantic__TestReturnClass__Return : IInterfacedMessage, IValueGetable
    {
        public SlimHttp.Interface.TestResult v;

        public Type GetInterfaceType() { return typeof(IPedantic); }

        public object Value { get { return v; } }
    }

    public interface IPedantic_NoReply
    {
        void TestCall();
        void TestOptional(System.Nullable<System.Int32> value);
        void TestTuple(System.Tuple<System.Int32, System.String> value);
        void TestParams(params System.Int32[] values);
        void TestPassClass(SlimHttp.Interface.TestParam param);
        void TestReturnClass(System.Int32 value, System.Int32 offset);
    }

    public class PedanticRef : InterfacedSlimActorRef, IPedantic_NoReply
    {
        public PedanticRef(ISlimActorRef actor, ISlimRequestWaiter requestWaiter, TimeSpan? timeout)
            : base(actor, requestWaiter, timeout)
        {
        }

        public IPedantic_NoReply WithNoReply()
        {
            return this;
        }

        public PedanticRef WithRequestWaiter(ISlimRequestWaiter requestWaiter)
        {
            return new PedanticRef(Actor, requestWaiter, Timeout);
        }

        public PedanticRef WithTimeout(TimeSpan? timeout)
        {
            return new PedanticRef(Actor, RequestWaiter, timeout);
        }

        public Task TestCall()
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new IPedantic__TestCall__Invoke {  }
            };
            return SendRequestAndWait(requestMessage);
        }

        public Task<System.Nullable<System.Int32>> TestOptional(System.Nullable<System.Int32> value)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new IPedantic__TestOptional__Invoke { value = (System.Nullable<System.Int32>)value }
            };
            return SendRequestAndReceive<System.Nullable<System.Int32>>(requestMessage);
        }

        public Task<System.Tuple<System.Int32, System.String>> TestTuple(System.Tuple<System.Int32, System.String> value)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new IPedantic__TestTuple__Invoke { value = (System.Tuple<System.Int32, System.String>)value }
            };
            return SendRequestAndReceive<System.Tuple<System.Int32, System.String>>(requestMessage);
        }

        public Task<System.Int32[]> TestParams(params System.Int32[] values)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new IPedantic__TestParams__Invoke { values = values }
            };
            return SendRequestAndReceive<System.Int32[]>(requestMessage);
        }

        public Task<System.String> TestPassClass(SlimHttp.Interface.TestParam param)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new IPedantic__TestPassClass__Invoke { param = param }
            };
            return SendRequestAndReceive<System.String>(requestMessage);
        }

        public Task<SlimHttp.Interface.TestResult> TestReturnClass(System.Int32 value, System.Int32 offset)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new IPedantic__TestReturnClass__Invoke { value = value, offset = offset }
            };
            return SendRequestAndReceive<SlimHttp.Interface.TestResult>(requestMessage);
        }

        void IPedantic_NoReply.TestCall()
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new IPedantic__TestCall__Invoke {  }
            };
            SendRequest(requestMessage);
        }

        void IPedantic_NoReply.TestOptional(System.Nullable<System.Int32> value)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new IPedantic__TestOptional__Invoke { value = (System.Nullable<System.Int32>)value }
            };
            SendRequest(requestMessage);
        }

        void IPedantic_NoReply.TestTuple(System.Tuple<System.Int32, System.String> value)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new IPedantic__TestTuple__Invoke { value = (System.Tuple<System.Int32, System.String>)value }
            };
            SendRequest(requestMessage);
        }

        void IPedantic_NoReply.TestParams(params System.Int32[] values)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new IPedantic__TestParams__Invoke { values = values }
            };
            SendRequest(requestMessage);
        }

        void IPedantic_NoReply.TestPassClass(SlimHttp.Interface.TestParam param)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new IPedantic__TestPassClass__Invoke { param = param }
            };
            SendRequest(requestMessage);
        }

        void IPedantic_NoReply.TestReturnClass(System.Int32 value, System.Int32 offset)
        {
            var requestMessage = new SlimRequestMessage
            {
                Message = new IPedantic__TestReturnClass__Invoke { value = value, offset = offset }
            };
            SendRequest(requestMessage);
        }
    }
}

#endregion
