// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Akka.Interfaced CodeGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;
using Akka.Interfaced;
using Akka.Actor;

#region Akka.Interfaced.SlimServer.IActorBoundChannel

namespace Akka.Interfaced.SlimServer
{
    [PayloadTable(typeof(IActorBoundChannel), PayloadTableKind.Request)]
    public static class IActorBoundChannel_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(BindActor_Invoke), typeof(BindActor_Return) },
                { typeof(BindType_Invoke), typeof(BindType_Return) },
                { typeof(UnbindActor_Invoke), typeof(UnbindActor_Return) },
                { typeof(UnbindType_Invoke), typeof(UnbindType_Return) },
            };
        }

        public class BindActor_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            public Akka.Actor.IActorRef actor;
            public Akka.Interfaced.SlimServer.TaggedType[] types;
            public Akka.Interfaced.SlimServer.ChannelClosedNotificationType channelClosedNotification;

            public Type GetInterfaceType()
            {
                return typeof(IActorBoundChannel);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IActorBoundChannel)__target).BindActor(actor, types, channelClosedNotification);
                return (IValueGetable)(new BindActor_Return { v = __v });
            }
        }

        public class BindActor_Return
            : IInterfacedPayload, IValueGetable
        {
            public System.Int32 v;

            public Type GetInterfaceType()
            {
                return typeof(IActorBoundChannel);
            }

            public object Value
            {
                get { return v; }
            }
        }

        public class BindType_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            public Akka.Actor.IActorRef actor;
            public Akka.Interfaced.SlimServer.TaggedType[] types;

            public Type GetInterfaceType()
            {
                return typeof(IActorBoundChannel);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IActorBoundChannel)__target).BindType(actor, types);
                return (IValueGetable)(new BindType_Return { v = __v });
            }
        }

        public class BindType_Return
            : IInterfacedPayload, IValueGetable
        {
            public System.Boolean v;

            public Type GetInterfaceType()
            {
                return typeof(IActorBoundChannel);
            }

            public object Value
            {
                get { return v; }
            }
        }

        public class UnbindActor_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            public Akka.Actor.IActorRef actor;

            public Type GetInterfaceType()
            {
                return typeof(IActorBoundChannel);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IActorBoundChannel)__target).UnbindActor(actor);
                return (IValueGetable)(new UnbindActor_Return { v = __v });
            }
        }

        public class UnbindActor_Return
            : IInterfacedPayload, IValueGetable
        {
            public System.Boolean v;

            public Type GetInterfaceType()
            {
                return typeof(IActorBoundChannel);
            }

            public object Value
            {
                get { return v; }
            }
        }

        public class UnbindType_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            public Akka.Actor.IActorRef actor;
            public System.Type[] types;

            public Type GetInterfaceType()
            {
                return typeof(IActorBoundChannel);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IActorBoundChannel)__target).UnbindType(actor, types);
                return (IValueGetable)(new UnbindType_Return { v = __v });
            }
        }

        public class UnbindType_Return
            : IInterfacedPayload, IValueGetable
        {
            public System.Boolean v;

            public Type GetInterfaceType()
            {
                return typeof(IActorBoundChannel);
            }

            public object Value
            {
                get { return v; }
            }
        }
    }

    public interface IActorBoundChannel_NoReply
    {
        void BindActor(Akka.Actor.IActorRef actor, Akka.Interfaced.SlimServer.TaggedType[] types, Akka.Interfaced.SlimServer.ChannelClosedNotificationType channelClosedNotification = Akka.Interfaced.SlimServer.ChannelClosedNotificationType.Default);
        void BindType(Akka.Actor.IActorRef actor, Akka.Interfaced.SlimServer.TaggedType[] types);
        void UnbindActor(Akka.Actor.IActorRef actor);
        void UnbindType(Akka.Actor.IActorRef actor, System.Type[] types);
    }

    public class ActorBoundChannelRef : InterfacedActorRef, IActorBoundChannel, IActorBoundChannel_NoReply
    {
        public ActorBoundChannelRef() : base(null)
        {
        }

        public ActorBoundChannelRef(IRequestTarget target) : base(target)
        {
        }

        public ActorBoundChannelRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public ActorBoundChannelRef(IActorRef actor) : base(new AkkaActorTarget(actor))
        {
        }

        public ActorBoundChannelRef(IActorRef actor, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(new AkkaActorTarget(actor), requestWaiter, timeout)
        {
        }

        public IActorRef Actor => ((AkkaActorTarget)Target)?.Actor;

        public IActorBoundChannel_NoReply WithNoReply()
        {
            return this;
        }

        public ActorBoundChannelRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new ActorBoundChannelRef(Target, requestWaiter, Timeout);
        }

        public ActorBoundChannelRef WithTimeout(TimeSpan? timeout)
        {
            return new ActorBoundChannelRef(Target, RequestWaiter, timeout);
        }

        public Task<System.Int32> BindActor(Akka.Actor.IActorRef actor, Akka.Interfaced.SlimServer.TaggedType[] types, Akka.Interfaced.SlimServer.ChannelClosedNotificationType channelClosedNotification = Akka.Interfaced.SlimServer.ChannelClosedNotificationType.Default)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IActorBoundChannel_PayloadTable.BindActor_Invoke { actor = actor, types = types, channelClosedNotification = channelClosedNotification }
            };
            return SendRequestAndReceive<System.Int32>(requestMessage);
        }

        public Task<System.Boolean> BindType(Akka.Actor.IActorRef actor, Akka.Interfaced.SlimServer.TaggedType[] types)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IActorBoundChannel_PayloadTable.BindType_Invoke { actor = actor, types = types }
            };
            return SendRequestAndReceive<System.Boolean>(requestMessage);
        }

        public Task<System.Boolean> UnbindActor(Akka.Actor.IActorRef actor)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IActorBoundChannel_PayloadTable.UnbindActor_Invoke { actor = actor }
            };
            return SendRequestAndReceive<System.Boolean>(requestMessage);
        }

        public Task<System.Boolean> UnbindType(Akka.Actor.IActorRef actor, System.Type[] types)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IActorBoundChannel_PayloadTable.UnbindType_Invoke { actor = actor, types = types }
            };
            return SendRequestAndReceive<System.Boolean>(requestMessage);
        }

        void IActorBoundChannel_NoReply.BindActor(Akka.Actor.IActorRef actor, Akka.Interfaced.SlimServer.TaggedType[] types, Akka.Interfaced.SlimServer.ChannelClosedNotificationType channelClosedNotification)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IActorBoundChannel_PayloadTable.BindActor_Invoke { actor = actor, types = types, channelClosedNotification = channelClosedNotification }
            };
            SendRequest(requestMessage);
        }

        void IActorBoundChannel_NoReply.BindType(Akka.Actor.IActorRef actor, Akka.Interfaced.SlimServer.TaggedType[] types)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IActorBoundChannel_PayloadTable.BindType_Invoke { actor = actor, types = types }
            };
            SendRequest(requestMessage);
        }

        void IActorBoundChannel_NoReply.UnbindActor(Akka.Actor.IActorRef actor)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IActorBoundChannel_PayloadTable.UnbindActor_Invoke { actor = actor }
            };
            SendRequest(requestMessage);
        }

        void IActorBoundChannel_NoReply.UnbindType(Akka.Actor.IActorRef actor, System.Type[] types)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IActorBoundChannel_PayloadTable.UnbindType_Invoke { actor = actor, types = types }
            };
            SendRequest(requestMessage);
        }
    }

    [AlternativeInterface(typeof(IActorBoundChannel))]
    public interface IActorBoundChannelSync : IInterfacedActorSync
    {
        System.Int32 BindActor(Akka.Actor.IActorRef actor, Akka.Interfaced.SlimServer.TaggedType[] types, Akka.Interfaced.SlimServer.ChannelClosedNotificationType channelClosedNotification = Akka.Interfaced.SlimServer.ChannelClosedNotificationType.Default);
        System.Boolean BindType(Akka.Actor.IActorRef actor, Akka.Interfaced.SlimServer.TaggedType[] types);
        System.Boolean UnbindActor(Akka.Actor.IActorRef actor);
        System.Boolean UnbindType(Akka.Actor.IActorRef actor, System.Type[] types);
    }
}

#endregion
#region Akka.Interfaced.SlimServer.IActorBoundGateway

namespace Akka.Interfaced.SlimServer
{
    [PayloadTable(typeof(IActorBoundGateway), PayloadTableKind.Request)]
    public static class IActorBoundGateway_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(OpenChannel_Invoke), typeof(OpenChannel_Return) },
            };
        }

        public class OpenChannel_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            public Akka.Actor.IActorRef actor;
            public System.Object channelClosedNotification;
            public Akka.Interfaced.SlimServer.TaggedType[] types;

            public Type GetInterfaceType()
            {
                return typeof(IActorBoundGateway);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IActorBoundGateway)__target).OpenChannel(actor, channelClosedNotification, types);
                return (IValueGetable)(new OpenChannel_Return { v = __v });
            }
        }

        public class OpenChannel_Return
            : IInterfacedPayload, IValueGetable
        {
            public System.String v;

            public Type GetInterfaceType()
            {
                return typeof(IActorBoundGateway);
            }

            public object Value
            {
                get { return v; }
            }
        }
    }

    public interface IActorBoundGateway_NoReply
    {
        void OpenChannel(Akka.Actor.IActorRef actor, System.Object channelClosedNotification, params Akka.Interfaced.SlimServer.TaggedType[] types);
    }

    public class ActorBoundGatewayRef : InterfacedActorRef, IActorBoundGateway, IActorBoundGateway_NoReply
    {
        public ActorBoundGatewayRef() : base(null)
        {
        }

        public ActorBoundGatewayRef(IRequestTarget target) : base(target)
        {
        }

        public ActorBoundGatewayRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public ActorBoundGatewayRef(IActorRef actor) : base(new AkkaActorTarget(actor))
        {
        }

        public ActorBoundGatewayRef(IActorRef actor, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(new AkkaActorTarget(actor), requestWaiter, timeout)
        {
        }

        public IActorRef Actor => ((AkkaActorTarget)Target)?.Actor;

        public IActorBoundGateway_NoReply WithNoReply()
        {
            return this;
        }

        public ActorBoundGatewayRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new ActorBoundGatewayRef(Target, requestWaiter, Timeout);
        }

        public ActorBoundGatewayRef WithTimeout(TimeSpan? timeout)
        {
            return new ActorBoundGatewayRef(Target, RequestWaiter, timeout);
        }

        public Task<System.String> OpenChannel(Akka.Actor.IActorRef actor, System.Object channelClosedNotification, params Akka.Interfaced.SlimServer.TaggedType[] types)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IActorBoundGateway_PayloadTable.OpenChannel_Invoke { actor = actor, channelClosedNotification = channelClosedNotification, types = types }
            };
            return SendRequestAndReceive<System.String>(requestMessage);
        }

        void IActorBoundGateway_NoReply.OpenChannel(Akka.Actor.IActorRef actor, System.Object channelClosedNotification, params Akka.Interfaced.SlimServer.TaggedType[] types)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IActorBoundGateway_PayloadTable.OpenChannel_Invoke { actor = actor, channelClosedNotification = channelClosedNotification, types = types }
            };
            SendRequest(requestMessage);
        }
    }

    [AlternativeInterface(typeof(IActorBoundGateway))]
    public interface IActorBoundGatewaySync : IInterfacedActorSync
    {
        System.String OpenChannel(Akka.Actor.IActorRef actor, System.Object channelClosedNotification, params Akka.Interfaced.SlimServer.TaggedType[] types);
    }
}

#endregion
#region Akka.Interfaced.SlimServer.IActorBoundChannelObserver

namespace Akka.Interfaced.SlimServer
{
    [PayloadTable(typeof(IActorBoundChannelObserver), PayloadTableKind.Notification)]
    public static class IActorBoundChannelObserver_PayloadTable
    {
        public static Type[] GetPayloadTypes()
        {
            return new Type[] {
                typeof(ChannelClose_Invoke),
            };
        }

        public class ChannelClose_Invoke : IInterfacedPayload, IInvokable
        {
            public Akka.Interfaced.SlimServer.TaggedType[] types;

            public Type GetInterfaceType()
            {
                return typeof(IActorBoundChannelObserver);
            }

            public void Invoke(object __target)
            {
                ((IActorBoundChannelObserver)__target).ChannelClose(types);
            }
        }
    }

    public class ActorBoundChannelObserver : InterfacedObserver, IActorBoundChannelObserver
    {
        public ActorBoundChannelObserver()
            : base(null, 0)
        {
        }

        public ActorBoundChannelObserver(INotificationChannel channel, int observerId = 0)
            : base(channel, observerId)
        {
        }

        public void ChannelClose(Akka.Interfaced.SlimServer.TaggedType[] types)
        {
            var payload = new IActorBoundChannelObserver_PayloadTable.ChannelClose_Invoke { types = types };
            Notify(payload);
        }
    }

    [AlternativeInterface(typeof(IActorBoundChannelObserver))]
    public interface IActorBoundChannelObserverAsync : IInterfacedObserverSync
    {
        Task ChannelClose(Akka.Interfaced.SlimServer.TaggedType[] types);
    }
}

#endregion
